config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :stories
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'about', to: 'pages#about'
  get 'impressum', to: 'pages#impressum'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :plan
  
  attr_accessor :stripe_card_token
  # If Pro user passes validation (email, password, etc.)
  # then call Stripe and stripe to set up a subscription
  # upon charging the customer's card.
  # Stripe responds back with customer data.
  # Store customer.id as the customer token and save the user.
  def save_with_subscription
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  # Whiteliste the folowwing form fields form so that we can process them, if coming from a Devise sign up form.
  before_action :configure_premitted_parameters, if: :devise_controller?
  
  protected
    def configure_premitted_parameters
       devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:stripe_card_token, :email, :password, :password_confirmation) } 
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  # Get request to /contact-us
  # Show new contact form
  def new
    @contact = Contact.new #großes C bei contact weil es danach im modell file sucht contact.rb
  end
  
  # Post request /contacts
  def create
    # Mass assignement of form fields into contact objects
    @contact = Contact.new(contact_params)
    # save the contact object to the database
    if @contact.save
      # Store form fields via parameter, into variables
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      # plug variables into catact Mailer email method and send email
      ContactMailer.contact_email(name, email, body).deliver
      # Store succes message in flash hash
      # and redirect to the new action
      flash[:success] = "Message sent."
      redirect_to new_contact_path
    else
      # if contact object doesn't save, 
      # store errors in flash hash,
      # and redirect to the new action
      flash[:danger] = @contact.errors.full_messages.join(", ") 
      redirect_to new_contact_path
    end
  end
  
  private
    # To collect data, from form, we need to use strong parameters
    # and whitelist the form fields //secruty feature
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   # GET request for / (mit nix hinter slash) which is our home page
   def about
      @basic_plan = Plan.find(1)
      @pro_plan = Plan.find(2)
   end

   def about
   end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def new
  end
  
  def create
    render plain: params[:story].inspect
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # Extend default Devise gem behavior so that 
  # users signing up with the Pro account (plan ID 2)
  # save with a special Stripe subscription function.
  # Otherwise Devise signs up user as usual. 
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_subscription
        else
          resource.save
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/contacts/new.html.erb
<div class="container">
    <div class="row">
        <h3 class="text-center">Contact Us</h3>
        
        <div class="col-md-4 col-md-offset-4">

            <div class="well">
                <%= form_for @contact do |f| %>
                    <div class="form-group">
                        <%= f.label :name %>
                        <%= f.text_field:name, class: 'form-control' %>
                    </div>
                    
                    <div class="form-group">
                        <%= f.label :email %>
                        <%= f.text_field:email, class: 'form-control' %>
                    </div>
                    
                    <div class="form-group">
                        <%= f.label :comments %>
                        <%= f.text_field:comments, class: 'form-control' %>
                    </div>
                    
                    <%= f.submit 'Submit', class: 'btn btn-default' %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Topside</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  </head>

  <body>
    <nav class="header">
      <nav class="navbar navbar-default navbar-static-top" role="navigation">
        <div class='container'>
          <div class="col-md-6">
            <div class="nav navbar-nav navbar-left">
              <div class="logo">
                <%= link_to root_path do %>
                  <%=image_tag("logo/logo_inverted.gif", size: "200x51", alt: "Example Image", class: "logo2")%>
                <% end %>
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="text-center">
              <div class="navbar-header">
                <div class="collapse navbar-collapse" id="main-nav-collapse">
                  <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to "Home", root_path %></li>
                    <li class="dropdown">
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#">Stories
                      <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><%= link_to "Alle Stories", about_path %></li>
                        <li><%= link_to "Neueste Stories", about_path %></li>
                        <li><%= link_to "Top Stories", about_path %></li>
                      </ul>
                    </li>
                    <li><%= link_to "Produkte", about_path %></li>
                    <li><%= link_to "Kontakt", new_contact_path %></li>
                  </ul>
                </div>
              </div>
            </div><!-- /.navbar-collapse -->
          </div>
        </div>
      </nav>    
    </nav>
    
    <div class="container">
      <% flash.each do |type, msg| %>
      <%=content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
    </div>
    
    <div class="grund">
      <%= yield %> <!Grund für jede seite die ganze datei und yield holt den rest der view files>
    </div>
  </body>
  
  <footer>
    <div class="container">
			<div class="footer_all">
				<div class="col-md-4">
				  <%=image_tag("logo/logo.gif", size: "150x38", alt: "Example Image", class: "footer_logo")%>
				  
 					<div class="footer_under_logo">
   					<p>Wir haben das Ziel dich mit unseren Produkten und Stories beim Sport zu unterstützen. So fällt dir der Sport leichter und du hast noch mehr Spaß am Sport. <br><br>
   					<strong>Topside</strong> - <strong>enjoy your sport.</strong></p>
 					</div>
 					
 					<div class="impressum_footer">
 					  <%= link_to "Impressum", impressum_path %><br>
 					  <%= link_to "Erfahre mehr über Topside", about_path %><br>
 					</div>
 					
					<address>
						<strong>Adresse:</strong><br>
						Kupferstraße 25<br>
						70565 Stuttgart<br>
					</address>
						<abbr title="Telefon"><strong>Telefon:</strong></abbr> +49 <br>
						<abbr title="Email:"><strong>Email:</strong></abbr> info@topside-sport.de <br>

					<div class="unten_login">
	          <% if user_signed_in? %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn nav_login" %>
            <% else %>
              <%= link_to "Log In", new_user_registration_path(plan: Plan.find(1).id), class: "btn btn-default navbar-btn nav_login" %>
            <% end %>
          </div>
				</div>
			</div>

					<div class="col-md-4 col_last">

						<div class="footer_mid">
							<h4>Instagramm Feed oder letzten Posts</h4>

							<div id="post-list-footer">
								<div class="spost clearfix">
									<div class="entry-c">
										<div class="entry-title">
											<h4><a href="#">Lorem ipsum dolor sit amet, consectetur</a></h4>
										</div>
										<ul class="entry-meta">
											<li>10th July 2014</li>
										</ul>
									</div>
								</div>

								<div class="spost clearfix">
									<div class="entry-c">
										<div class="entry-title">
											<h4><a href="#">Elit Assumenda vel amet dolorum quasi</a></h4>
										</div>
										<ul class="entry-meta">
											<li>10th July 2014</li>
										</ul>
									</div>
								</div>

								<div class="spost clearfix">
									<div class="entry-c">
										<div class="entry-title">
											<h4><a href="#">Debitis nihil placeat, illum est nisi</a></h4>
										</div>
										<ul class="entry-meta">
											<li>10th July 2014</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-4">
						<div class="fb_footer">
              <div class="fb-page" data-href="https://www.facebook.com/Topside-2082532521973737/" 
                data-tabs="timeline" data-width="250" data-height="350" data-small-header="true" 
                data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
                  <blockquote cite="https://www.facebook.com/Topside-2082532521973737/" class="fb-xfbml-parse-ignore">
                    <a href="https://www.facebook.com/Topside-2082532521973737/">Topside</a>
                  </blockquote>
                </div>
						</div>
					</div>
				</div><!-- .footer-widgets-wrap end -->
			</div>
		</div>
  </footer>
</html>

app/views/pages/about.html.erb
<div class='container text-center'>
    <h1>Impressum</h1>
    <p>Wir sind foodtags.de. Exklusive Einkaufmöglichkeiten! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, architecto, impedit, fugiat pariatur non sed dolorem quae at aliquid minus repudiandae aut in quibusdam quidem earum beatae corporis. Fugit, blanditiis!</p>
</div>


<div class="container home-signup-links">
  <div class="row">
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Standard Mitgliedschaft</h2>
        <h4>Umsonst Registrieren für die Stardard Mitgliedschaft in unserer Community</h4>
        <br/>
        <%= link_to "Sign up with Basic", new_user_registration_path(plan: Plan.find(1).id), class: "btn btn-primary btn-lg btn-block" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <h2 class ="text-center">Pro Membership</h2>
        <h4>Registriere dich bei unserer Community für 10€/Monat um von allen Vorteilen zu profitieren</h4>
        <br/>
        <%= link_to "Sign up with Pro", new_user_registration_path(plan: Plan.find(2).id), class: "btn btn-success btn-lg btn-block" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
  <h1>ENJOY YOUR SPORT</h1>
</div>
<div class="home_welcome_text text-center">
  <h2>Willkommen auf Topside.info</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, autem, cupiditate, quidem inventore vel labore earum esse blanditiis numquam molestiae eos nihil explicabo suscipit rem voluptatem fugit sunt ipsam mollitia.</p>
</div>

<div class="container home-grid">
  <div class="text-center">
    <h2>Die neusten Stories</h2>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="well">
        <nav class="text-center home-inner-grid">
        <%= link_to root_path do %>
          <%=image_tag("stories/1.jpg", alt: "Example Image", class: "pic-home-grid")%>
        <% end %>
        <%= link_to "Wie geht es nur weiter", about_path, class: "home-grid-link" %>
        </nav>      
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <nav class="text-center home-inner-grid">
        <%= link_to root_path do %>
          <%=image_tag("stories/2.jpg", alt: "Example Image", class: "pic-home-grid")%>
        <% end %>
        <%= link_to "Das Jubiläum", about_path, class: "home-grid-link" %>
        </nav>      
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <nav class="text-center home-inner-grid">
        <%= link_to root_path do %>
          <%=image_tag("stories/3.jpg", alt: "Example Image", class: "pic-home-grid")%>
        <% end %>
        <%= link_to "Top 10 Ficker in Deutschland", about_path, class: "home-grid-link" %>
        </nav>      
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <nav class="text-center home-inner-grid">
        <%= link_to root_path do %>
          <%=image_tag("stories/10.jpg", alt: "Example Image", class: "pic-home-grid")%>
        <% end %>
        <%= link_to "Top 10 Joggerstrecken in Deutschland und der Welt", about_path, class: "home-grid-link" %>
        </nav>      
      </div>
    </div>
  </div>
</div>
    
<div class="container home-grid">
  <div class="text-center">
    <h2>Top Stories</h2>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="well">
        <nav class="text-center home-inner-grid">
        <%= link_to root_path do %>
          <%=image_tag("stories/1.jpg", alt: "Example Image", class: "pic-home-grid")%>
        <% end %>
        <%= link_to "Wie geht es nur weiter", about_path, class: "home-grid-link" %>
        </nav>      
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <nav class="text-center home-inner-grid">
        <%= link_to root_path do %>
          <%=image_tag("stories/2.jpg", alt: "Example Image", class: "pic-home-grid")%>
        <% end %>
        <%= link_to "Das Jubiläum", about_path, class: "home-grid-link" %>
        </nav>      
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <nav class="text-center home-inner-grid">
        <%= link_to root_path do %>
          <%=image_tag("stories/3.jpg", alt: "Example Image", class: "pic-home-grid")%>
        <% end %>
        <%= link_to "Top 10 Ficker in Deutschland", about_path, class: "home-grid-link" %>
        </nav>      
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <nav class="text-center home-inner-grid">
        <%= link_to root_path do %>
          <%=image_tag("stories/10.jpg", alt: "Example Image", class: "pic-home-grid")%>
        <% end %>
        <%= link_to "Top 10 Joggerstrecken in Deutschland und der Welt", about_path, class: "home-grid-link" %>
        </nav>      
      </div>
    </div>
  </div>

</div>

app/views/pages/impressum.html.erb
<div class='container text-center'>
    <h1>Impressum</h1>
    <p><br><br>Angaben gemäß § 5 TMG:<br><br> 

4mate<br>
Inhaber: Manuel Eynollahiargaghy<br>
Geschäftsanschrift:<br>
Kupferstraße 25<br>
70565 Stuttgart<br><br>

Umsatzsteuer-Identifikationsnummer gemäß §27 a Umsatzsteuergesetz:<br>
DE308531663<br><br>

Kontaktaufnahme<br>
Eine elektronische Kontaktaufnahme ist unter der E-Mail-Adresse info@topside-sport.de möglich.<br><br>

Telefon:<br>
+49 (0) <br>

ONLINE-STREITBEILEGUNG<br>
Seit dem 9. Januar 2016 können gemäß der EU-Verordnung 524/2013 Streitigkeiten zwischen Verbrauchern und Händlern und/oder Dienstleistern im Zusammenhang von Online-Kaufverträgen oder Online-Dienstleistungsverträgen über eine europaweite Online-Plattform beigelegt werden.<br><br>

Diese Plattform ist über nachfolgenden Link erreichbar:<br>
http://ec.europa.eu/consumers/odr/<br><br>

Urheber- und Nutzungsrechte<br>
Die durch die Seitenbetreiber erstellten Inhalte, Werke und bereitgestellten Informationen unterliegen dem deutschen Urheber- und Leistungsschutzrecht. Die Rechte an den auf dieser Webseite bereitgestellten Inhalten und Werken liegen bei Manuel Eynollahiargaghy.<br>
Unveränderte Auszüge oder Inhalte aus dieser Webseite können für persönliche, private und nicht kommerzielle Zwecke ausgedruckt oder auf sonstige Weise vorübergehend gespeichert werden, sofern hierbei sämtliche Urheberrechts- und Eigentumshinweise unverändert übernommen werden.<br>
Davon abgesehen darf diese Webseite weder ganz noch auszugsweise ohne die vorherige schriftliche Zustimmung von Manuel Eynollahiargaghy kopiert, modifiziert oder auf Medien jedweder Art öffentlich dargeboten oder neu veröffentlicht werden; insbesondere in Frames oder iFrames.<br><br>

Verwendung von Daten<br>
Wir weisen darauf hin, dass die Verwendung der Kontaktdaten des Impressums zur gewerblichen Werbung ausdrücklich nicht erwünscht ist, es sei denn, wir hatten zuvor unsere schriftliche Einwilligung erteilt oder es besteht bereits eine Geschäftsbeziehung. Wir und alle auf dieser Webseite genannten Personen widersprechen hiermit jeder kommerziellen Verwendung und Weitergabe der Daten.</p>
</div>

app/views/stories/new.html.erb
<h1>New Story</h1>

<!--vielleicht article statt story-->

<%= form_for :story, url: stories_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
  <%= f.submit %>
  </p>
<% end %>